# Generated by Django 5.2.1 on 2025-06-02 14:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('straw_catalog', '0004_alter_order_user_alter_orderitem_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dish',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
