# Generated by Django 5.2.1 on 2025-06-02 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('straw_catalog', '0005_dish_created_at_dish_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='rating',
        ),
    ]
