# Generated by Django 5.2.1 on 2025-06-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('straw_catalog', '0006_remove_dish_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
